
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>KVInfo Frontend</title>
    </head>
    <body>
        <h1>Welcome to KVInfoSysBund</h1>
        <p>This is the static frontend served via NGINX.</p>
    </body>
    </html>