name: Frontend CI

on:
  workflow_call:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Lint & Test
        run: |
          cd frontend
          npm run lint && npm test

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Frontend Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/kvinfo-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/kvinfo-frontend:latest
